// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: adx.proto

#import <Foundation/Foundation.h>

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "AdService.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
  // 兼容不同的 CocoaPods/头文件路径布局，优先使用标准路径，其次使用本地或 Pods 相对路径
  #if __has_include(<ProtoRPC/ProtoService.h>)
    #import <ProtoRPC/ProtoService.h>
    #import <ProtoRPC/ProtoRPCLegacy.h>
  #elif __has_include("ProtoService.h")
    #import "ProtoService.h"
    #import "ProtoRPCLegacy.h"
  #elif __has_include("../../Pods/Headers/Public/gRPC-ProtoRPC/ProtoService.h")
    #import "../../Pods/Headers/Public/gRPC-ProtoRPC/ProtoService.h"
    #import "../../Pods/Headers/Public/gRPC-ProtoRPC/ProtoRPCLegacy.h"
  #else
    // 无法找到 ProtoRPC 头文件时，回退到协议仅模式以避免编译中断
    #define GPB_GRPC_PROTOCOL_ONLY 1
  #endif

  #if __has_include(<RxLibrary/GRXWriteable.h>)
    #import <RxLibrary/GRXWriteable.h>
    #import <RxLibrary/GRXWriter.h>
  #elif __has_include("GRXWriteable.h")
    #import "GRXWriteable.h"
    #import "GRXWriter.h"
  #elif __has_include("../../Pods/Headers/Public/RxLibrary/GRXWriteable.h")
    #import "../../Pods/Headers/Public/RxLibrary/GRXWriteable.h"
    #import "../../Pods/Headers/Public/RxLibrary/GRXWriter.h"
  #endif
#endif

@class YAdAdResponse;
@class YAdBidRequest;
@class YAdLogRequest;
@class YAdLogResponse;
@class YAdRouteRequest;
@class YAdRouteResponse;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
// Optional import for Protobuf Any; not strictly required for these RPC declarations.
#if __has_include(<Protobuf/GPBAny.pbobjc.h>)
  #import <Protobuf/GPBAny.pbobjc.h>
#elif __has_include("GPBAny.pbobjc.h")
  #import "GPBAny.pbobjc.h"
#elif __has_include("../../Pods/Headers/Public/Protobuf/GPBAny.pbobjc.h")
  #import "../../Pods/Headers/Public/Protobuf/GPBAny.pbobjc.h"
#else
  // Fallback: forward declare to satisfy references if any occur.
  @class GPBAny;
#endif
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol YAdAdService2 <NSObject>

#pragma mark RequestAd(BidRequest) returns (AdResponse)

/**
 * RequestAd handles an ad request from a client.
 */
- (GRPCUnaryProtoCall *)requestAdWithMessage:(YAdBidRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark LogEvent(LogRequest) returns (LogResponse)

/**
 * LogEvent handles logging of impression and click events.
 */
- (GRPCUnaryProtoCall *)logEventWithMessage:(YAdLogRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark RouteRequest(RouteRequest) returns (RouteResponse)

/**
 * RouteRequest returns server addresses for SDK routing/caching.
 */
- (GRPCUnaryProtoCall *)routeRequestWithMessage:(YAdRouteRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol YAdAdService <NSObject>

#pragma mark RequestAd(BidRequest) returns (AdResponse)

/**
 * RequestAd handles an ad request from a client.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)requestAdWithRequest:(YAdBidRequest *)request handler:(void(^)(YAdAdResponse *_Nullable response, NSError *_Nullable error))handler;

/**
 * RequestAd handles an ad request from a client.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToRequestAdWithRequest:(YAdBidRequest *)request handler:(void(^)(YAdAdResponse *_Nullable response, NSError *_Nullable error))handler;


#pragma mark LogEvent(LogRequest) returns (LogResponse)

/**
 * LogEvent handles logging of impression and click events.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)logEventWithRequest:(YAdLogRequest *)request handler:(void(^)(YAdLogResponse *_Nullable response, NSError *_Nullable error))handler;

/**
 * LogEvent handles logging of impression and click events.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToLogEventWithRequest:(YAdLogRequest *)request handler:(void(^)(YAdLogResponse *_Nullable response, NSError *_Nullable error))handler;


#pragma mark RouteRequest(RouteRequest) returns (RouteResponse)

/**
 * RouteRequest returns server addresses for SDK routing/caching.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)routeRequestWithRequest:(YAdRouteRequest *)request handler:(void(^)(YAdRouteResponse *_Nullable response, NSError *_Nullable error))handler;

/**
 * RouteRequest returns server addresses for SDK routing/caching.
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToRouteRequestWithRequest:(YAdRouteRequest *)request handler:(void(^)(YAdRouteResponse *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface YAdAdService : GRPCProtoService<YAdAdService2, YAdAdService>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END
