// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// clang-format off
// source: adx.proto

// Protobuf header import with robust fallbacks for different CocoaPods setups
#if __has_include(<Protobuf/GPBProtocolBuffers.h>)
 #import <Protobuf/GPBProtocolBuffers.h>
#elif __has_include("GPBProtocolBuffers.h")
 #import "GPBProtocolBuffers.h"
#elif __has_include("../../Pods/Headers/Public/Protobuf/GPBProtocolBuffers.h")
 // Relative path fallback for CocoaPods public headers
 #import "../../Pods/Headers/Public/Protobuf/GPBProtocolBuffers.h"
#elif __has_include("../../Pods/Protobuf/objectivec/GPBProtocolBuffers.h")
 // Fallback to the Protobuf pod's source headers location
 #import "../../Pods/Protobuf/objectivec/GPBProtocolBuffers.h"
#else
 #error "Protobuf headers not found. Ensure the Protobuf pod is integrated or header search paths include Pods/Headers/Public/Protobuf."
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 40311
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 40311 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class YAdAdSlot;
@class YAdApp;
@class YAdAppData;
@class YAdBid;
@class YAdDevice;
@class YAdEventTrack;
@class YAdGeo;
@class YAdImage;
@class YAdMaterialMeta;
@class YAdMiniProgram;
@class YAdProgressTimeTracks;
@class YAdProgressTrack;
@class YAdSldMap;
@class YAdUser;
@class YAdVideo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - YAdAdxRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface YAdAdxRoot : GPBRootObject
@end

#pragma mark - YAdRouteRequest

typedef GPB_ENUM(YAdRouteRequest_FieldNumber) {
  YAdRouteRequest_FieldNumber_Type = 1,
  YAdRouteRequest_FieldNumber_Ua = 2,
  YAdRouteRequest_FieldNumber_Make = 3,
  YAdRouteRequest_FieldNumber_Model = 4,
  YAdRouteRequest_FieldNumber_Os = 5,
  YAdRouteRequest_FieldNumber_Osv = 6,
  YAdRouteRequest_FieldNumber_Carrier = 7,
  YAdRouteRequest_FieldNumber_Connection = 8,
  YAdRouteRequest_FieldNumber_Oaid = 9,
  YAdRouteRequest_FieldNumber_Imei = 10,
  YAdRouteRequest_FieldNumber_AndroidId = 11,
  YAdRouteRequest_FieldNumber_Imsi = 12,
  YAdRouteRequest_FieldNumber_Idfa = 13,
  YAdRouteRequest_FieldNumber_Mac = 14,
};

/**
 * RouteRequest represents device/app info used to fetch routing addresses.
 **/
GPB_FINAL @interface YAdRouteRequest : GPBMessage

/** 设备类型，0-未知，1-phone，2-tablet，3-其他 */
@property(nonatomic, readwrite) int32_t type;

/** User-Agent */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ua;

/** 设备制造商 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *make;

/** 设备型号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

/** 操作系统，iOS=1，Android=2 */
@property(nonatomic, readwrite) int32_t os;

/** 操作系统版本号 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *osv;

/** 运营商编码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *carrier;

/** 网络类型，0-未知，1-ethernet，2-2G，3-3G，4-4G，5-5G，6-wifi */
@property(nonatomic, readwrite) int32_t connection;

/** OAID，Android10 以上必传 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *oaid;

/** IMEI 原文，Android10 以上取不到可不传或空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imei;

/** Android ID 原文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *androidId;

/** IMSI，可选 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *imsi;

/** IDFA 原文 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *idfa;

/** MAC 地址，可选 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mac;

@end

#pragma mark - YAdRouteResponse

typedef GPB_ENUM(YAdRouteResponse_FieldNumber) {
  YAdRouteResponse_FieldNumber_Code = 1,
  YAdRouteResponse_FieldNumber_RequestAddrArray = 2,
};

/**
 * RouteResponse returns code and list of routing addresses.
 **/
GPB_FINAL @interface YAdRouteResponse : GPBMessage

/** 返回代码，200-成功 */
@property(nonatomic, readwrite) int32_t code;

/** 广告请求地址数组 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *requestAddrArray;
/** The number of items in @c requestAddrArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger requestAddrArray_Count;

@end

#pragma mark - YAdLogRequest

typedef GPB_ENUM(YAdLogRequest_FieldNumber) {
  YAdLogRequest_FieldNumber_LogUri = 1,
};

/**
 * LogRequest represents a log event request.
 **/
GPB_FINAL @interface YAdLogRequest : GPBMessage

/** Log Uri */
@property(nonatomic, readwrite, copy, null_resettable) NSString *logUri;

@end

#pragma mark - YAdLogResponse

typedef GPB_ENUM(YAdLogResponse_FieldNumber) {
  YAdLogResponse_FieldNumber_Success = 1,
  YAdLogResponse_FieldNumber_Message = 2,
};

/**
 * LogResponse represents the response to a log event request.
 **/
GPB_FINAL @interface YAdLogResponse : GPBMessage

/** Whether the event was successfully logged */
@property(nonatomic, readwrite) BOOL success;

/** Optional message, especially useful for errors */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@end

#pragma mark - YAdBidRequest

typedef GPB_ENUM(YAdBidRequest_FieldNumber) {
  YAdBidRequest_FieldNumber_RequestId = 1,
  YAdBidRequest_FieldNumber_AdSlot = 2,
  YAdBidRequest_FieldNumber_App = 3,
  YAdBidRequest_FieldNumber_Device = 4,
  YAdBidRequest_FieldNumber_User = 5,
  YAdBidRequest_FieldNumber_Support302 = 6,
  YAdBidRequest_FieldNumber_Deeplink = 7,
  YAdBidRequest_FieldNumber_Sdkver = 8,
};

/**
 * BidRequest represents a bid request from a client.
 **/
GPB_FINAL @interface YAdBidRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

@property(nonatomic, readwrite, strong, null_resettable) YAdAdSlot *adSlot;
/** Test to see if @c adSlot has been set. */
@property(nonatomic, readwrite) BOOL hasAdSlot;

@property(nonatomic, readwrite, strong, null_resettable) YAdApp *app;
/** Test to see if @c app has been set. */
@property(nonatomic, readwrite) BOOL hasApp;

@property(nonatomic, readwrite, strong, null_resettable) YAdDevice *device;
/** Test to see if @c device has been set. */
@property(nonatomic, readwrite) BOOL hasDevice;

@property(nonatomic, readwrite, strong, null_resettable) YAdUser *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite) int32_t support302;

@property(nonatomic, readwrite) int32_t deeplink;

@property(nonatomic, readwrite) int32_t sdkver;

@end

#pragma mark - YAdAdSlot

typedef GPB_ENUM(YAdAdSlot_FieldNumber) {
  YAdAdSlot_FieldNumber_SlotId = 1,
  YAdAdSlot_FieldNumber_AdType = 2,
  YAdAdSlot_FieldNumber_W = 3,
  YAdAdSlot_FieldNumber_H = 4,
  YAdAdSlot_FieldNumber_CreativeType = 5,
  YAdAdSlot_FieldNumber_MinDuration = 6,
  YAdAdSlot_FieldNumber_MaxDuration = 7,
  YAdAdSlot_FieldNumber_Skip = 8,
  YAdAdSlot_FieldNumber_SkipAfter = 9,
  YAdAdSlot_FieldNumber_VideoType = 10,
  YAdAdSlot_FieldNumber_BannerType = 11,
};

/**
 * AdSlot object.
 **/
GPB_FINAL @interface YAdAdSlot : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *slotId;

@property(nonatomic, readwrite) int32_t adType;

@property(nonatomic, readwrite) int32_t w;

@property(nonatomic, readwrite) int32_t h;

@property(nonatomic, readwrite) int32_t creativeType;

@property(nonatomic, readwrite) int32_t minDuration;

@property(nonatomic, readwrite) int32_t maxDuration;

@property(nonatomic, readwrite) int32_t skip;

@property(nonatomic, readwrite) int32_t skipAfter;

@property(nonatomic, readwrite) int32_t videoType;

@property(nonatomic, readwrite) int32_t bannerType;

@end

#pragma mark - YAdApp

typedef GPB_ENUM(YAdApp_FieldNumber) {
  YAdApp_FieldNumber_AppId = 1,
  YAdApp_FieldNumber_Name = 2,
  YAdApp_FieldNumber_Bundle = 3,
  YAdApp_FieldNumber_Ver = 4,
};

/**
 * App object.
 **/
GPB_FINAL @interface YAdApp : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bundle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ver;

@end

#pragma mark - YAdDevice

typedef GPB_ENUM(YAdDevice_FieldNumber) {
  YAdDevice_FieldNumber_Type = 1,
  YAdDevice_FieldNumber_Dnt = 2,
  YAdDevice_FieldNumber_Ua = 3,
  YAdDevice_FieldNumber_Make = 4,
  YAdDevice_FieldNumber_Model = 5,
  YAdDevice_FieldNumber_Os = 6,
  YAdDevice_FieldNumber_Osv = 7,
  YAdDevice_FieldNumber_H = 8,
  YAdDevice_FieldNumber_W = 9,
  YAdDevice_FieldNumber_Carrier = 10,
  YAdDevice_FieldNumber_Connection = 11,
  YAdDevice_FieldNumber_Oaid = 12,
  YAdDevice_FieldNumber_OaidMd5 = 13,
  YAdDevice_FieldNumber_Imei = 14,
  YAdDevice_FieldNumber_ImeiMd5 = 15,
  YAdDevice_FieldNumber_ImeiSha1 = 16,
  YAdDevice_FieldNumber_AndroidId = 17,
  YAdDevice_FieldNumber_AndroidIdmd5 = 18,
  YAdDevice_FieldNumber_AndroidIdsha1 = 19,
  YAdDevice_FieldNumber_Imsi = 20,
  YAdDevice_FieldNumber_Idfa = 21,
  YAdDevice_FieldNumber_IdfaMd5 = 22,
  YAdDevice_FieldNumber_IdfaSha1 = 23,
  YAdDevice_FieldNumber_CaidsArray = 24,
  YAdDevice_FieldNumber_Mac = 25,
  YAdDevice_FieldNumber_MacMd5 = 26,
  YAdDevice_FieldNumber_SysMemory = 27,
  YAdDevice_FieldNumber_SysDiskSize = 28,
  YAdDevice_FieldNumber_DeviceName = 29,
  YAdDevice_FieldNumber_DeviceNameMd5 = 30,
  YAdDevice_FieldNumber_BootMark = 31,
  YAdDevice_FieldNumber_UpdateMark = 32,
  YAdDevice_FieldNumber_DeviceInitializeTime = 33,
  YAdDevice_FieldNumber_BootTimeSec = 34,
  YAdDevice_FieldNumber_OsUpdateTimeSec = 35,
  YAdDevice_FieldNumber_Geo = 36,
  YAdDevice_FieldNumber_Ip = 37,
  YAdDevice_FieldNumber_Ipv6 = 38,
  YAdDevice_FieldNumber_Ssid = 39,
  YAdDevice_FieldNumber_Bssid = 40,
  YAdDevice_FieldNumber_Paid = 41,
  YAdDevice_FieldNumber_Aaid = 42,
  YAdDevice_FieldNumber_Dpi = 43,
  YAdDevice_FieldNumber_Density = 44,
  YAdDevice_FieldNumber_Country = 45,
  YAdDevice_FieldNumber_Language = 46,
  YAdDevice_FieldNumber_SysVer = 47,
  YAdDevice_FieldNumber_AppStorePackage = 48,
  YAdDevice_FieldNumber_HwagVer = 49,
  YAdDevice_FieldNumber_HmsVer = 50,
  YAdDevice_FieldNumber_HwModel = 51,
  YAdDevice_FieldNumber_HwName = 52,
  YAdDevice_FieldNumber_HwNameMd5 = 53,
  YAdDevice_FieldNumber_HwMachine = 54,
  YAdDevice_FieldNumber_Orientation = 55,
  YAdDevice_FieldNumber_Ppi = 56,
  YAdDevice_FieldNumber_VivoAppStoreVersion = 57,
  YAdDevice_FieldNumber_HwAppStoreVersion = 58,
  YAdDevice_FieldNumber_OppoAppStoreVersion = 59,
  YAdDevice_FieldNumber_Caid = 60,
  YAdDevice_FieldNumber_CaidVersion = 61,
  YAdDevice_FieldNumber_CaidVender = 62,
  YAdDevice_FieldNumber_CpuCoreNum = 63,
  YAdDevice_FieldNumber_CpuFreq = 64,
  YAdDevice_FieldNumber_CountryCode = 65,
  YAdDevice_FieldNumber_TimeZone = 66,
};

/**
 * Device object.
 **/
GPB_FINAL @interface YAdDevice : GPBMessage

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) int32_t dnt;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ua;

@property(nonatomic, readwrite, copy, null_resettable) NSString *make;

@property(nonatomic, readwrite, copy, null_resettable) NSString *model;

@property(nonatomic, readwrite) int32_t os;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osv;

@property(nonatomic, readwrite) int32_t h;

@property(nonatomic, readwrite) int32_t w;

@property(nonatomic, readwrite, copy, null_resettable) NSString *carrier;

@property(nonatomic, readwrite) int32_t connection;

@property(nonatomic, readwrite, copy, null_resettable) NSString *oaid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *oaidMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imei;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imeiMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imeiSha1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *androidId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *androidIdmd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *androidIdsha1;

@property(nonatomic, readwrite, copy, null_resettable) NSString *imsi;

@property(nonatomic, readwrite, copy, null_resettable) NSString *idfa;

@property(nonatomic, readwrite, copy, null_resettable) NSString *idfaMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *idfaSha1;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *caidsArray;
/** The number of items in @c caidsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger caidsArray_Count;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mac;

@property(nonatomic, readwrite, copy, null_resettable) NSString *macMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sysMemory;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sysDiskSize;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceNameMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bootMark;

@property(nonatomic, readwrite, copy, null_resettable) NSString *updateMark;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceInitializeTime;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bootTimeSec;

@property(nonatomic, readwrite, copy, null_resettable) NSString *osUpdateTimeSec;

@property(nonatomic, readwrite, strong, null_resettable) YAdGeo *geo;
/** Test to see if @c geo has been set. */
@property(nonatomic, readwrite) BOOL hasGeo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ipv6;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ssid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bssid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *aaid;

@property(nonatomic, readwrite) int32_t dpi;

@property(nonatomic, readwrite) float density;

@property(nonatomic, readwrite, copy, null_resettable) NSString *country;

@property(nonatomic, readwrite, copy, null_resettable) NSString *language;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sysVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appStorePackage;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwagVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hmsVer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwModel;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwNameMd5;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwMachine;

@property(nonatomic, readwrite) int32_t orientation;

@property(nonatomic, readwrite) int32_t ppi;

@property(nonatomic, readwrite, copy, null_resettable) NSString *vivoAppStoreVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hwAppStoreVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *oppoAppStoreVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *caid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *caidVersion;

@property(nonatomic, readwrite, copy, null_resettable) NSString *caidVender;

@property(nonatomic, readwrite) int32_t cpuCoreNum;

@property(nonatomic, readwrite) float cpuFreq;

@property(nonatomic, readwrite, copy, null_resettable) NSString *countryCode;

@property(nonatomic, readwrite) int32_t timeZone;

@end

#pragma mark - YAdGeo

typedef GPB_ENUM(YAdGeo_FieldNumber) {
  YAdGeo_FieldNumber_Lat = 1,
  YAdGeo_FieldNumber_Lon = 2,
  YAdGeo_FieldNumber_City = 3,
  YAdGeo_FieldNumber_Province = 4,
  YAdGeo_FieldNumber_District = 5,
  YAdGeo_FieldNumber_Timestamp = 6,
};

/**
 * // Geo object.
 **/
GPB_FINAL @interface YAdGeo : GPBMessage

@property(nonatomic, readwrite) float lat;

@property(nonatomic, readwrite) float lon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *city;

@property(nonatomic, readwrite, copy, null_resettable) NSString *province;

@property(nonatomic, readwrite, copy, null_resettable) NSString *district;

/** UTC offset. */
@property(nonatomic, readwrite) int32_t timestamp;

@end

#pragma mark - YAdUser

typedef GPB_ENUM(YAdUser_FieldNumber) {
  YAdUser_FieldNumber_UserId = 1,
  YAdUser_FieldNumber_Tags = 2,
  YAdUser_FieldNumber_Gender = 3,
  YAdUser_FieldNumber_Age = 4,
  YAdUser_FieldNumber_Keywords = 5,
  YAdUser_FieldNumber_AppListArray = 6,
};

/**
 * User object.
 **/
GPB_FINAL @interface YAdUser : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *tags;

@property(nonatomic, readwrite, copy, null_resettable) NSString *gender;

@property(nonatomic, readwrite) int32_t age;

@property(nonatomic, readwrite, copy, null_resettable) NSString *keywords;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *appListArray;
/** The number of items in @c appListArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger appListArray_Count;

@end

#pragma mark - YAdAdResponse

typedef GPB_ENUM(YAdAdResponse_FieldNumber) {
  YAdAdResponse_FieldNumber_Code = 1,
  YAdAdResponse_FieldNumber_RequestId = 2,
  YAdAdResponse_FieldNumber_BidsArray = 3,
  YAdAdResponse_FieldNumber_DelayTime = 4,
};

/**
 * AdResponse represents an ad response to a client.
 **/
GPB_FINAL @interface YAdAdResponse : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *requestId;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<YAdBid*> *bidsArray;
/** The number of items in @c bidsArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger bidsArray_Count;

@property(nonatomic, readwrite) int32_t delayTime;

@end

#pragma mark - YAdSldMap

typedef GPB_ENUM(YAdSldMap_FieldNumber) {
  YAdSldMap_FieldNumber_Unknown = 1,
  YAdSldMap_FieldNumber_Click = 2,
  YAdSldMap_FieldNumber_Hclick = 3,
  YAdSldMap_FieldNumber_Shake = 4,
  YAdSldMap_FieldNumber_Gesture = 5,
  YAdSldMap_FieldNumber_Twist = 6,
  YAdSldMap_FieldNumber_Erase = 7,
};

GPB_FINAL @interface YAdSldMap : GPBMessage

@property(nonatomic, readwrite) int32_t unknown;

@property(nonatomic, readwrite) int32_t click;

@property(nonatomic, readwrite) int32_t hclick;

@property(nonatomic, readwrite) int32_t shake;

@property(nonatomic, readwrite) int32_t gesture;

@property(nonatomic, readwrite) int32_t twist;

@property(nonatomic, readwrite) int32_t erase;

@end

#pragma mark - YAdBid

typedef GPB_ENUM(YAdBid_FieldNumber) {
  YAdBid_FieldNumber_Adid = 1,
  YAdBid_FieldNumber_Crid = 2,
  YAdBid_FieldNumber_Price = 3,
  YAdBid_FieldNumber_PddAdid = 4,
  YAdBid_FieldNumber_NurlArray = 5,
  YAdBid_FieldNumber_LurlArray = 6,
  YAdBid_FieldNumber_Creative = 7,
  YAdBid_FieldNumber_App = 8,
  YAdBid_FieldNumber_ClickAction = 9,
  YAdBid_FieldNumber_Landing = 10,
  YAdBid_FieldNumber_Source = 11,
  YAdBid_FieldNumber_SourceLogo = 12,
  YAdBid_FieldNumber_Deeplink = 13,
  YAdBid_FieldNumber_EventTrack = 14,
  YAdBid_FieldNumber_ExpirationTime = 15,
  YAdBid_FieldNumber_InteractionMode = 16,
  YAdBid_FieldNumber_RedEnvelopeRain = 17,
  YAdBid_FieldNumber_Countdown = 18,
  YAdBid_FieldNumber_AdCache = 19,
  YAdBid_FieldNumber_Ext = 20,
  YAdBid_FieldNumber_SldMap = 21,
  YAdBid_FieldNumber_ShakeSensitivity = 22,
};

/**
 * Bid object.
 **/
GPB_FINAL @interface YAdBid : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *adid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *crid;

@property(nonatomic, readwrite) int32_t price;

@property(nonatomic, readwrite, copy, null_resettable) NSString *pddAdid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *nurlArray;
/** The number of items in @c nurlArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger nurlArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *lurlArray;
/** The number of items in @c lurlArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger lurlArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) YAdMaterialMeta *creative;
/** Test to see if @c creative has been set. */
@property(nonatomic, readwrite) BOOL hasCreative;

@property(nonatomic, readwrite, strong, null_resettable) YAdAppData *app;
/** Test to see if @c app has been set. */
@property(nonatomic, readwrite) BOOL hasApp;

@property(nonatomic, readwrite) int32_t clickAction;

@property(nonatomic, readwrite, copy, null_resettable) NSString *landing;

@property(nonatomic, readwrite, copy, null_resettable) NSString *source;

@property(nonatomic, readwrite, copy, null_resettable) NSString *sourceLogo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deeplink;

@property(nonatomic, readwrite, strong, null_resettable) YAdEventTrack *eventTrack;
/** Test to see if @c eventTrack has been set. */
@property(nonatomic, readwrite) BOOL hasEventTrack;

@property(nonatomic, readwrite) int32_t expirationTime;

@property(nonatomic, readwrite) int32_t interactionMode;

@property(nonatomic, readwrite) int32_t redEnvelopeRain;

@property(nonatomic, readwrite) int32_t countdown;

@property(nonatomic, readwrite) int32_t adCache;

@property(nonatomic, readwrite, strong, null_resettable) GPBAny *ext;
/** Test to see if @c ext has been set. */
@property(nonatomic, readwrite) BOOL hasExt;

@property(nonatomic, readwrite, strong, null_resettable) YAdSldMap *sldMap;
/** Test to see if @c sldMap has been set. */
@property(nonatomic, readwrite) BOOL hasSldMap;

@property(nonatomic, readwrite) int32_t shakeSensitivity;

@end

#pragma mark - YAdMaterialMeta

typedef GPB_ENUM(YAdMaterialMeta_FieldNumber) {
  YAdMaterialMeta_FieldNumber_Title = 1,
  YAdMaterialMeta_FieldNumber_Description_p = 2,
  YAdMaterialMeta_FieldNumber_Cta = 3,
  YAdMaterialMeta_FieldNumber_Rating = 4,
  YAdMaterialMeta_FieldNumber_Icon = 5,
  YAdMaterialMeta_FieldNumber_Image = 6,
  YAdMaterialMeta_FieldNumber_ImagesArray = 7,
  YAdMaterialMeta_FieldNumber_ImageMode = 8,
  YAdMaterialMeta_FieldNumber_Video = 9,
  YAdMaterialMeta_FieldNumber_HtmlSnippet = 10,
  YAdMaterialMeta_FieldNumber_MiniProgram = 11,
  YAdMaterialMeta_FieldNumber_Render = 12,
  YAdMaterialMeta_FieldNumber_RenderTpl = 13,
};

/**
 * MaterialMeta object.
 **/
GPB_FINAL @interface YAdMaterialMeta : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *description_p;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cta;

@property(nonatomic, readwrite) float rating;

@property(nonatomic, readwrite, strong, null_resettable) YAdImage *icon;
/** Test to see if @c icon has been set. */
@property(nonatomic, readwrite) BOOL hasIcon;

@property(nonatomic, readwrite, strong, null_resettable) YAdImage *image;
/** Test to see if @c image has been set. */
@property(nonatomic, readwrite) BOOL hasImage;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<YAdImage*> *imagesArray;
/** The number of items in @c imagesArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@property(nonatomic, readwrite) int32_t imageMode;

@property(nonatomic, readwrite, strong, null_resettable) YAdVideo *video;
/** Test to see if @c video has been set. */
@property(nonatomic, readwrite) BOOL hasVideo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *htmlSnippet;

@property(nonatomic, readwrite, strong, null_resettable) YAdMiniProgram *miniProgram;
/** Test to see if @c miniProgram has been set. */
@property(nonatomic, readwrite) BOOL hasMiniProgram;

@property(nonatomic, readwrite) int32_t render;

@property(nonatomic, readwrite) int32_t renderTpl;

@end

#pragma mark - YAdImage

typedef GPB_ENUM(YAdImage_FieldNumber) {
  YAdImage_FieldNumber_URL = 1,
  YAdImage_FieldNumber_W = 2,
  YAdImage_FieldNumber_H = 3,
  YAdImage_FieldNumber_AspectRatio = 4,
};

/**
 * Image object.
 **/
GPB_FINAL @interface YAdImage : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t w;

@property(nonatomic, readwrite) int32_t h;

@property(nonatomic, readwrite) double aspectRatio;

@end

#pragma mark - YAdVideo

typedef GPB_ENUM(YAdVideo_FieldNumber) {
  YAdVideo_FieldNumber_URL = 1,
  YAdVideo_FieldNumber_Duration = 2,
  YAdVideo_FieldNumber_Size = 3,
  YAdVideo_FieldNumber_Resolution = 4,
  YAdVideo_FieldNumber_Cover = 5,
  YAdVideo_FieldNumber_Coverw = 6,
  YAdVideo_FieldNumber_Coverh = 7,
  YAdVideo_FieldNumber_Title = 8,
  YAdVideo_FieldNumber_Desc = 9,
  YAdVideo_FieldNumber_Icon = 10,
  YAdVideo_FieldNumber_AfterHtml = 11,
  YAdVideo_FieldNumber_LandingURL = 12,
  YAdVideo_FieldNumber_VideoMute = 13,
  YAdVideo_FieldNumber_VideoAutoplay = 14,
  YAdVideo_FieldNumber_RewardMode = 15,
  YAdVideo_FieldNumber_RewardContent = 16,
  YAdVideo_FieldNumber_RewardName = 17,
  YAdVideo_FieldNumber_RewardNum = 18,
  YAdVideo_FieldNumber_RewardCallback = 19,
};

/**
 * Video object.
 **/
GPB_FINAL @interface YAdVideo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) float duration;

@property(nonatomic, readwrite) float size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resolution;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cover;

@property(nonatomic, readwrite) int32_t coverw;

@property(nonatomic, readwrite) int32_t coverh;

@property(nonatomic, readwrite, copy, null_resettable) NSString *title;

@property(nonatomic, readwrite, copy, null_resettable) NSString *desc;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *afterHtml;

@property(nonatomic, readwrite, copy, null_resettable) NSString *landingURL;

@property(nonatomic, readwrite) int32_t videoMute;

@property(nonatomic, readwrite) int32_t videoAutoplay;

@property(nonatomic, readwrite) int32_t rewardMode;

@property(nonatomic, readwrite) int32_t rewardContent;

@property(nonatomic, readwrite, copy, null_resettable) NSString *rewardName;

@property(nonatomic, readwrite) int32_t rewardNum;

@property(nonatomic, readwrite) int32_t rewardCallback;

@end

#pragma mark - YAdMiniProgram

typedef GPB_ENUM(YAdMiniProgram_FieldNumber) {
  YAdMiniProgram_FieldNumber_MpId = 1,
  YAdMiniProgram_FieldNumber_MpUserName = 2,
  YAdMiniProgram_FieldNumber_MpPath = 3,
};

/**
 * MiniProgram object.
 **/
GPB_FINAL @interface YAdMiniProgram : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *mpId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mpUserName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mpPath;

@end

#pragma mark - YAdAppData

typedef GPB_ENUM(YAdAppData_FieldNumber) {
  YAdAppData_FieldNumber_Name = 1,
  YAdAppData_FieldNumber_Bundle = 2,
  YAdAppData_FieldNumber_Ver = 3,
  YAdAppData_FieldNumber_Icon = 4,
  YAdAppData_FieldNumber_Developer = 5,
  YAdAppData_FieldNumber_PrivacyURL = 6,
  YAdAppData_FieldNumber_Permission = 7,
  YAdAppData_FieldNumber_Intro = 8,
  YAdAppData_FieldNumber_Feature = 9,
  YAdAppData_FieldNumber_Size = 10,
  YAdAppData_FieldNumber_PaymentType = 11,
};

/**
 * AppData object.
 **/
GPB_FINAL @interface YAdAppData : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *bundle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *ver;

@property(nonatomic, readwrite, copy, null_resettable) NSString *icon;

@property(nonatomic, readwrite, copy, null_resettable) NSString *developer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *privacyURL;

@property(nonatomic, readwrite, copy, null_resettable) NSString *permission;

@property(nonatomic, readwrite, copy, null_resettable) NSString *intro;

@property(nonatomic, readwrite, copy, null_resettable) NSString *feature;

@property(nonatomic, readwrite) double size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *paymentType;

@end

#pragma mark - YAdEventTrack

typedef GPB_ENUM(YAdEventTrack_FieldNumber) {
  YAdEventTrack_FieldNumber_ImpTracksArray = 1,
  YAdEventTrack_FieldNumber_ClkTracksArray = 2,
  YAdEventTrack_FieldNumber_AppUninstalledArray = 3,
  YAdEventTrack_FieldNumber_AppInstalledArray = 4,
  YAdEventTrack_FieldNumber_DplTryArray = 5,
  YAdEventTrack_FieldNumber_DplSuccessArray = 6,
  YAdEventTrack_FieldNumber_DplFailedArray = 7,
  YAdEventTrack_FieldNumber_FallBackTracksArray = 8,
  YAdEventTrack_FieldNumber_DlTracksArray = 9,
  YAdEventTrack_FieldNumber_InstallTracksArray = 10,
  YAdEventTrack_FieldNumber_DlStartTracksArray = 11,
  YAdEventTrack_FieldNumber_InstallStartTracksArray = 12,
  YAdEventTrack_FieldNumber_GdtTracks = 13,
  YAdEventTrack_FieldNumber_ProgressTracks = 14,
  YAdEventTrack_FieldNumber_AutoplayArray = 15,
  YAdEventTrack_FieldNumber_VideoPauseArray = 16,
  YAdEventTrack_FieldNumber_VideoResumeArray = 17,
  YAdEventTrack_FieldNumber_SkipTracksArray = 18,
  YAdEventTrack_FieldNumber_StopTracksArray = 19,
  YAdEventTrack_FieldNumber_ProgressTimeTracksArray = 20,
  YAdEventTrack_FieldNumber_VideoMuteArray = 21,
  YAdEventTrack_FieldNumber_VideoUnmuteArray = 22,
  YAdEventTrack_FieldNumber_IncentiveCallbackArray = 23,
  YAdEventTrack_FieldNumber_UcClkTracksArray = 24,
  YAdEventTrack_FieldNumber_InstalledOpenArray = 25,
  YAdEventTrack_FieldNumber_InstallFailedArray = 26,
  YAdEventTrack_FieldNumber_DlPauseArray = 27,
  YAdEventTrack_FieldNumber_DlResumeArray = 28,
  YAdEventTrack_FieldNumber_DlDeleteArray = 29,
  YAdEventTrack_FieldNumber_VideoStopArray = 30,
  YAdEventTrack_FieldNumber_VideoReadyArray = 31,
  YAdEventTrack_FieldNumber_VideoLoadErrorArray = 32,
  YAdEventTrack_FieldNumber_VideoErrorArray = 33,
  YAdEventTrack_FieldNumber_VideoReplayArray = 34,
  YAdEventTrack_FieldNumber_VideoFullArray = 35,
  YAdEventTrack_FieldNumber_VideoExitFullArray = 36,
};

/**
 * EventTrack object.
 **/
GPB_FINAL @interface YAdEventTrack : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *impTracksArray;
/** The number of items in @c impTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger impTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *clkTracksArray;
/** The number of items in @c clkTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger clkTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *appUninstalledArray;
/** The number of items in @c appUninstalledArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger appUninstalledArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *appInstalledArray;
/** The number of items in @c appInstalledArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger appInstalledArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dplTryArray;
/** The number of items in @c dplTryArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dplTryArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dplSuccessArray;
/** The number of items in @c dplSuccessArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dplSuccessArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dplFailedArray;
/** The number of items in @c dplFailedArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dplFailedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *fallBackTracksArray;
/** The number of items in @c fallBackTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger fallBackTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dlTracksArray;
/** The number of items in @c dlTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dlTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *installTracksArray;
/** The number of items in @c installTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger installTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dlStartTracksArray;
/** The number of items in @c dlStartTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dlStartTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *installStartTracksArray;
/** The number of items in @c installStartTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger installStartTracksArray_Count;

@property(nonatomic, readwrite) int32_t gdtTracks;

@property(nonatomic, readwrite, strong, null_resettable) YAdProgressTrack *progressTracks;
/** Test to see if @c progressTracks has been set. */
@property(nonatomic, readwrite) BOOL hasProgressTracks;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *autoplayArray;
/** The number of items in @c autoplayArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger autoplayArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoPauseArray;
/** The number of items in @c videoPauseArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoPauseArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoResumeArray;
/** The number of items in @c videoResumeArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoResumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *skipTracksArray;
/** The number of items in @c skipTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger skipTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *stopTracksArray;
/** The number of items in @c stopTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger stopTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<YAdProgressTimeTracks*> *progressTimeTracksArray;
/** The number of items in @c progressTimeTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger progressTimeTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoMuteArray;
/** The number of items in @c videoMuteArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoMuteArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoUnmuteArray;
/** The number of items in @c videoUnmuteArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoUnmuteArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *incentiveCallbackArray;
/** The number of items in @c incentiveCallbackArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger incentiveCallbackArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *ucClkTracksArray;
/** The number of items in @c ucClkTracksArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger ucClkTracksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *installedOpenArray;
/** The number of items in @c installedOpenArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger installedOpenArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *installFailedArray;
/** The number of items in @c installFailedArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger installFailedArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dlPauseArray;
/** The number of items in @c dlPauseArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dlPauseArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dlResumeArray;
/** The number of items in @c dlResumeArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dlResumeArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *dlDeleteArray;
/** The number of items in @c dlDeleteArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger dlDeleteArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoStopArray;
/** The number of items in @c videoStopArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoStopArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoReadyArray;
/** The number of items in @c videoReadyArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoReadyArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoLoadErrorArray;
/** The number of items in @c videoLoadErrorArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoLoadErrorArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoErrorArray;
/** The number of items in @c videoErrorArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoErrorArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoReplayArray;
/** The number of items in @c videoReplayArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoReplayArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoFullArray;
/** The number of items in @c videoFullArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoFullArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *videoExitFullArray;
/** The number of items in @c videoExitFullArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger videoExitFullArray_Count;

@end

#pragma mark - YAdProgressTrack

typedef GPB_ENUM(YAdProgressTrack_FieldNumber) {
  YAdProgressTrack_FieldNumber_StartArray = 1,
  YAdProgressTrack_FieldNumber_FirstQuartileArray = 2,
  YAdProgressTrack_FieldNumber_MidPointArray = 3,
  YAdProgressTrack_FieldNumber_ThirdQuartileArray = 4,
  YAdProgressTrack_FieldNumber_CompleteArray = 5,
};

/**
 * ProgressTrack object
 **/
GPB_FINAL @interface YAdProgressTrack : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *startArray;
/** The number of items in @c startArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger startArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *firstQuartileArray;
/** The number of items in @c firstQuartileArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger firstQuartileArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *midPointArray;
/** The number of items in @c midPointArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger midPointArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *thirdQuartileArray;
/** The number of items in @c thirdQuartileArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger thirdQuartileArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *completeArray;
/** The number of items in @c completeArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger completeArray_Count;

@end

#pragma mark - YAdProgressTimeTracks

typedef GPB_ENUM(YAdProgressTimeTracks_FieldNumber) {
  YAdProgressTimeTracks_FieldNumber_Millisec = 1,
  YAdProgressTimeTracks_FieldNumber_URLArray = 2,
};

/**
 * ProgressTrack object
 **/
GPB_FINAL @interface YAdProgressTimeTracks : GPBMessage

@property(nonatomic, readwrite) int32_t millisec;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *URLArray;
/** The number of items in @c URLArray without causing the container to be created. */
@property(nonatomic, readonly) NSUInteger URLArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)

// clang-format on
